name: Home task 2'

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            
            - name: Setup dotnet 7.0
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '7.0.x'

            - name: Display dotnet version
              run: dotnet --version
            
            - name: Install requipments
              run: dotnet add packege Newtonsoft.Json --version 12.0.1
